# Esse arquivo é responsável por agendar a execução do Cypress em um intervalo de tempo específico.
# O cron é a ferramenta que vai agendar em que momento vai ser realizado o test no github.

name: Cypress-api-schedule
on:
  schedule:
    - cron: "* * * * *"
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
